export default {
  staff: [
    {
      name: 'Pamela Greenberg',
      bio: 'Pamela has been working in immersive technology education for 3 years after 10 years as a psychotherapist.  As Program Director for Galvanize San Francisco she works behind the scenes to support the Student Services and Instructor teams so that students have a great experience from Admissions all the way through Career Services.',
      picture: 'http://i.imgur.com/7697g0T.jpg?1',
      role: 'Program Director',
      link: 'https://www.linkedin.com/in/pamelagreenberg/',
      tag: '',
    },
    {
      name: 'Jenny Engard',
      bio: 'Jenny Engard is a people engager and empath with a passionate desire to make people aware of their own superpowers and happiness potential. She has worked in the entertainment, beauty and education industries as a musician, artist, consultant, career coach, executive assistant and now as the Student Success Manager at Galvanize. When she\'s not busy wrangling biographical data or keeping culture moving, Jenny can be found engaging in useless trivia, building arts and crafts, or performing with her karaoke family.',
      picture: 'http://i.imgur.com/XZRSXFv.png',
      role: 'Student Success Manager',
      link: 'https://www.linkedin.com/in/jennyengard/',
      tag: '',
    },
    {
      name: 'Mary Ann Barge',
      bio: 'Mary Ann Barge helps Galvanize grads break into the tech industry. She is driven by helping people from different backgrounds find jobs that they love, and helping them make the most of their careers. From 2011-2015, she founded and ran a recruitment and career consultancy based in London, and once returning to the Bay Area, worked at a YC startup that aimed to overhaul the technical recruitment process. In her spare time, she drinks wine, plays with George, and reads depressing Russian literature.',
      picture: 'http://i.imgur.com/EtFzFm3.png',
      role: 'Career Services Manager',
      link: 'https://www.linkedin.com/in/maryannbarge/',
      tag: '',
    },
    {
      name: 'James Van',
      bio: 'James is excited to help students transition back into the workforce. He currently works with Galvanize students and grads to find their next pathway to a happy and productive career. Prior to Galvanize, James worked as Career Services Manager at HULT International Business school, where he worked with graduate business students from over 100 different countries. Other experience includes UC Berkeley and Golden Gate University. Prior to switching to higher education, James worked as a technical recruiter for 9 years in San Francisco and Silicon Valley to place talent in tech-related companies. James holds a Masters Degree in Counseling Education with an emphasis on Career Counseling. Aside from his day job, he owns his own surf sports store, selling windsurf, surf, and SUP gear. Any leftover free time is spent on the water, with his family (one daughter, one dog), or friends. ',
      picture: 'http://i.imgur.com/wJASric.jpg',
      role: 'Career Services Manager',
      link: 'https://www.linkedin.com/in/jamesvan/',
      tag: '',
    },
    {
      name: 'Andrew Fitch',
      bio: 'Andrew Fitch works as the Evangelist for Galvanize San Francisco. His focus is on speaking to the SF tech community about Galvanize\'s educational programs. Previous to his work at Galvanize, he worked  in Marketing Management for coding, test prep, and screen acting education companies. If you don\'t see Andrew running an event or sponsoring a conference, you\'ll likely find him out exploring the greatness the Bay Area has to offer.',
      picture: 'http://i.imgur.com/yPZ5Cuu.jpg',
      role: 'Galvanize Evangelist',
      link: 'https://www.linkedin.com/in/andrew-fitch-b9655928/',
      tag: '',
    },
    {
      name: 'Liz Howard',
      bio: 'Liz Howard is an engineer with over 15 years of experience, and a teacher with over 5 years of experience, and a civil rights activist. She started her first software company at 15, wrote the EBT fraud prevention system for 8 of the top 10 banks in the country, and helped found an engineering school for women. She continues to teach, write software, and write curriculum at Galvanize.',
      picture: 'http://i.imgur.com/4KDvuHc.jpg',
      role: 'Curriculum Developer',
      link: 'https://www.linkedin.com/in/annhoward/',
      tag: '',
    },
    {
      name: 'Nir Kaldero',
      bio: 'Nir Kaldero is the Director of Data Science, and serves as a faculty member in the GalvanizeU-University of New Haven\'s Master of Science in Data Science program. Prior to joining Galvanize, as a data scientist and economist, Nir was the Lead Instructor for Data Science at General Assembly, a scholar in the Economics Department at the University of California, Berkeley, and an independent data science consultant. Nir completed PhD coursework in Economics, with application to Industrial Organizations, Finance and Marketing at the University of California, Berkeley, and holds a BA in Economics and Business Administration from IDC Herzliya in Tel Aviv, Israel.  ',
      picture: 'http://i.imgur.com/Yrqb88q.jpg',
      role: 'Director of Data Science',
      link: 'https://www.linkedin.com/in/nirkaldero/',
      tag: 'DSI',
    },
    {
      name: 'Isaac Laughlin',
      bio: 'Isaac Laughlin teaches Data Science theory and practice as part of Galvanize\'s 12-week Data Science Immersive course. Prior to joining Galvanize he worked on industry-leading models for automotive price prediction at TrueCar.com, built Creds.me--a crowd-sourced platform for predicting the future, and was an RA at the Federal Reserve Board. He has a Masters Degree in Operations Research from the University of Wisconsin Madison.',
      picture: 'http://i.imgur.com/zZxMuZ9.png?2',
      role: 'Principle Instructor, Data Scientist',
      link: 'https://www.linkedin.com/in/ilaughlin/',
      tag: 'DSI',
    },
    {
      name: 'Brad Jacobs',
      bio: 'Brad\'s passion for exploring data springs from his experience studying millions of stars across hundreds of nearby galaxies observed with the Hubble Space Telescope. When not pondering galaxies Brad spent his time teaching astronomy in various classroom and outreach settings. After deciding to pursue work involving more earthbound datasets, he joined Cohort-1 (zero-indexed) of Zipfian Academy, the precursor to Galvanize\'s Data Science Immersive. Brad then went to work as a machine learning engineer at a consumer analytics startup before choosing to rejoin Galvanize as an instructor.',
      picture: 'http://i.imgur.com/GGqgbg9.png',
      role: 'Instructor, Data Scientist',
      link: 'https://www.linkedin.com/in/bradleyajacobs/',
      tag: 'DSI',
    },
    {
      name: 'Cary Goltermann',
      bio: 'Cary Goltermann has a background in math and physics and started programming while attending University of Colorado Boulder. While at CU, he accepted a Teaching Assistantship, where he got his chops as a teacher, teaching C programming language and Matlab. Cary went on to attend Galvanize’s Data Science Immersive in Denver in 2015 and was immediately hired as a Data Scientist in Residence, to assist in teaching curriculum to other cohorts and, soon thereafter, Cary as a Data Scientist, Associate Instructor. He has a passion for both the theoretical aspects of data science algorithms and the practical ones associated with practicing efficient data science in code. Moreover, he loves sharing that passion through teaching.',
      picture: 'http://i.imgur.com/HSV52NV.png',
      role: 'Instructor, Data Scientist',
      link: 'https://www.linkedin.com/in/carygoltermann/',
      tag: 'DSI',
    },
    {
      name: 'Ivan Corneillet',
      bio: 'Ivan Corneillet comes to you from France with a background in math, physics, computer science, and electrical engineering.  Ivan worked in the high-performance computing space for many years designing hardware and developing software before going back to school and earn an MBA.  At the Wharton school, Ivan was drawn to all the (hard) finance quant classes and soon became an unofficial and then an official teaching assistant for the school.  His move towards Data science was a natural step as it brings together his passion in theory, practice, and teaching.',
      picture: 'http://i.imgur.com/Rv2rFRN.jpg',
      role: 'Instructor, Data Scientist',
      link: 'https://www.linkedin.com/in/ivancorneillet/',
      tag: 'DSI',
    },
    {
      name: 'Moses Marsh',
      bio: 'My background is in physics research and I first came to Galvanize as a student hoping to find the best way to apply my analysis skills toward optimizing real-world networks like traffic systems and power grids. I found the learning environment here to be so extraordinary that I stayed on as an instructor. I\'m thrilled to work with the future of data science (you!).',
      picture: 'http://i.imgur.com/XfY8e1n.jpg',
      role: 'Associate Instructor, Data Scientist',
      link: 'https://www.linkedin.com/in/moses-marsh-4a6aa1100/',
      tag: 'DSI',
    },
    {
      name: 'Tyler Bettilyon',
      bio: 'Tyler Bettilyon is a programming generalist with a passion for all things analytical. He started programming in high school and continued that education with a Bachelors of Computer Science from the University of Utah. Has been a teacher and mentor his whole life and has been gainfully employed as a private tutor, teaching assistant, debate coach, and now instructor of web development at Galvanize. In addition to his time as a teacher, Tyler has spent 5 years as a professional software engineer both in San Francisco and in his hometown of Salt Lake City.',
      picture: 'http://i.imgur.com/Ok7CZu8.jpg?3',
      role: 'Principle Instructor, Web Development',
      link: 'https://www.linkedin.com/in/tylerbettilyon/',
      tag: 'WDI',
    },
    {
      name: 'Hamid Aghdaee',
      bio: 'Hamid Aghdaee has been doing web development professionally for over a dozen years, most recently as a Senior Software Engineer at Pandora. He\'s invested the time it takes to learn the ins and out of the craft and the industry, and he\'s very excited about the tremendous amount of innovation currently on display in the field. Teaching and mentoring developers has been one of the most rewarding aspects of his work, and he\'s thrilled to bring his experience and passion for teaching to Galvanize!',
      picture: 'http://i.imgur.com/guITk8T.jpg',
      role: 'Lead Instructor, Web Development',
      link: 'https://www.linkedin.com/in/hamid-aghdaee-442548/',
      tag: 'WDI',
    },
    {
      name: 'Josh Wyatt',
      bio: 'Josh Wyatt has been educating Web Developers for almost three years. As a self-taught Developer and short-term immersive program graduate himself, Josh is a master of technical learning, communication, and content delivery. Josh is also a lifelong student of Philosophy and found his way into tech after studies in Aikido, zen and the Feldenkrais Method of Somatic Education. He love humans and the things they build, thinking and how they think. He has been in the Bay Area for almost 20 years and currently lives in Oakland with his partner and daughter. ',
      picture: 'http://i.imgur.com/voQbEKS.jpg?4',
      role: 'Lead Instructor, Web Development',
      link: 'https://www.linkedin.com/in/joshwyattjw/',
      tag: 'WDI',
    },
    {
      name: 'Robert Murray',
      bio: 'Robert has spent the last two decades building applications for the music, hospitality, fashion, and finance industries. Throughout his career, Robert has embraced opportunities to keep pace with the industry and learn new technologies. Previously, Robert worked as a Freelance Full-Stack iOS Engineer while based in Austin, TX. Robert is currently an Instructor for the Galvanize\'s Web Development Immersive program and based in the SF area. Robert hails from Jamaica and has also lived in Atlanta, New York City, and Miami where he was a founding member of RefreshMiami.',
      picture: 'http://i.imgur.com/3fddEZv.png',
      role: 'Instructor, Web Development',
      link: 'https://www.linkedin.com/in/robtmurray/',
      tag: 'WDI',
    },
    {
      name: 'Parker Lewis',
      bio: 'Parker is an instructor and web developer at Galvanize. He specializes in web development (specifically working most often with Javascript) but his interests extend to artificial intelligence, computer architecture, and robotics. Before coming to Galvanize Parker studied philosophy and Chinese at UC Davis and is a former student of the Galvanize Web Development Immersive program. ',
      picture: 'http://i.imgur.com/ODvLksq.jpg?1',
      role: 'Instructor, Web Development',
      link: 'https://www.linkedin.com/in/parker-lewis/',
      tag: 'WDI',
    }, {
      name: 'Namkai Fairfield',
      bio: '',
      picture: 'http://i.imgur.com/s0DJczy.jpg?1',
      role: 'Resident, Web Development',
      link: 'https://www.linkedin.com/in/namkai/',
      tag: 'WDI',
    },
  ],
  query: '',
  tag: 'ALL',
};
